#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("JPA.Android.Resource", IsApplication=true)]

namespace JPA.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.barColor = global::JPA.Android.Resource.Attribute.barColor;
			global::AndroidHUD.Resource.Attribute.barLength = global::JPA.Android.Resource.Attribute.barLength;
			global::AndroidHUD.Resource.Attribute.barWidth = global::JPA.Android.Resource.Attribute.barWidth;
			global::AndroidHUD.Resource.Attribute.circleColor = global::JPA.Android.Resource.Attribute.circleColor;
			global::AndroidHUD.Resource.Attribute.delayMillis = global::JPA.Android.Resource.Attribute.delayMillis;
			global::AndroidHUD.Resource.Attribute.radius = global::JPA.Android.Resource.Attribute.radius;
			global::AndroidHUD.Resource.Attribute.rimColor = global::JPA.Android.Resource.Attribute.rimColor;
			global::AndroidHUD.Resource.Attribute.rimWidth = global::JPA.Android.Resource.Attribute.rimWidth;
			global::AndroidHUD.Resource.Attribute.spinSpeed = global::JPA.Android.Resource.Attribute.spinSpeed;
			global::AndroidHUD.Resource.Attribute.text = global::JPA.Android.Resource.Attribute.text;
			global::AndroidHUD.Resource.Attribute.textColor = global::JPA.Android.Resource.Attribute.textColor;
			global::AndroidHUD.Resource.Attribute.textSize = global::JPA.Android.Resource.Attribute.textSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::JPA.Android.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::JPA.Android.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::JPA.Android.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::JPA.Android.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::JPA.Android.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::JPA.Android.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::JPA.Android.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::JPA.Android.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::JPA.Android.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::JPA.Android.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::JPA.Android.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::JPA.Android.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::JPA.Android.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_barColor = global::JPA.Android.Resource.Styleable.ProgressWheel_barColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_barLength = global::JPA.Android.Resource.Styleable.ProgressWheel_barLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_barWidth = global::JPA.Android.Resource.Styleable.ProgressWheel_barWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_circleColor = global::JPA.Android.Resource.Styleable.ProgressWheel_circleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_delayMillis = global::JPA.Android.Resource.Styleable.ProgressWheel_delayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_radius = global::JPA.Android.Resource.Styleable.ProgressWheel_radius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_rimColor = global::JPA.Android.Resource.Styleable.ProgressWheel_rimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_rimWidth = global::JPA.Android.Resource.Styleable.ProgressWheel_rimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_spinSpeed = global::JPA.Android.Resource.Styleable.ProgressWheel_spinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_text = global::JPA.Android.Resource.Styleable.ProgressWheel_text;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_textColor = global::JPA.Android.Resource.Styleable.ProgressWheel_textColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_textSize = global::JPA.Android.Resource.Styleable.ProgressWheel_textSize;
			global::PerpetualMobile.Storage.Resource.String.library_name = global::JPA.Android.Resource.String.library_name;
			global::Base.Android.Resource.String.library_name = global::JPA.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int barColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int barLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int barWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int circleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int delayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int radius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int rimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int rimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int spinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int text = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int textColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int textSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_search = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_search = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_share = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_drawer = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_errorstatus = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_successstatus = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int roundedbg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int roundedbgdark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int splash = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int Companies = 2131230720;
			
			// aapt resource value: 0x7f08000f
			public const int Description = 2131230735;
			
			// aapt resource value: 0x7f080002
			public const int Name = 2131230722;
			
			// aapt resource value: 0x7f080011
			public const int Publications = 2131230737;
			
			// aapt resource value: 0x7f08000e
			public const int Title = 2131230734;
			
			// aapt resource value: 0x7f080014
			public const int action_share = 2131230740;
			
			// aapt resource value: 0x7f080001
			public const int company_image = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int content_frame = 2131230728;
			
			// aapt resource value: 0x7f080012
			public const int description = 2131230738;
			
			// aapt resource value: 0x7f080007
			public const int drawer_layout = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int left_drawer = 2131230731;
			
			// aapt resource value: 0x7f080009
			public const int load_status = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int load_status_message = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int loadingImage = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int loadingProgressBar = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int loadingProgressWheel = 2131230726;
			
			// aapt resource value: 0x7f08000c
			public const int menu_image = 2131230732;
			
			// aapt resource value: 0x7f080010
			public const int pub_list = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int search = 2131230739;
			
			// aapt resource value: 0x7f080004
			public const int textViewStatus = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int title = 2131230733;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CompaniesGrid = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Company = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loading = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loadingimage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loadingprogress = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Navigation = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NavigationItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NavigationItemOld = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Publication = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PublicationsList = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PublicationView = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int options_menu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int publication_menu = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int by_company = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int companies = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int drawer_close = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int drawer_open = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int loading = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int main_title = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int menu = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int search_hint = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int search_results = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int search_title = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int share = 2131034125;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int searchable = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_barColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_barLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_barWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_circleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_delayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_radius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_rimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_rimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_spinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_text = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_textColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_textSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
